name: snakemod
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2=2.4.1
  - curl=7.71.1
  - samtools=1.10
  - seqtk=1.3
  - snakefmt=0.1.5
  - snakemake=5.25
  - spades=3.14.1
  - sra-tools=2.10.1
